spring:
  application:
    name: service-one
  cloud:
    discovery:
      enabled: true
      service-id: service-one
  actuator:
    endpoints:
      web:
        exposure:
          include: '*'

server:
  port: 8081
